### PR TITLE
Set height of left popup menu to make it work with bottom taskbar

### PR DESCRIPTION
**Pull request by timothytylee**
This patch makes left popup menu visible when status icon in located inside taskbar at bottom of screen.

### CODE REVIEW

**Comment by tbursztyka** [comment]
This is not a proper fix, as the requested size is fixed. This will not always work: depending on the gtk style, the font size etc... it might be too big or too small.

The solution would be to calculate properly the real size of the menu (its items, the labels, etc etc...) and request this calculated size. But that's something Gtk+ does already internally for any kind of menus and ... fails when it comes to systray menus. So it can be done in the app, but the real fix should be in Gtk+ framework.

Thus I am not merging this patch. It can be used as a hack, but not more.

**Comment by timothytylee** [comment]
The menu size is now calculated from the actual items inside it.

**Comment by tbursztyka** [comment]
Sounds nice!
One minor comment: don't do the patch on top of the old one, redo it on top of master.

Does this verify to work well on KDE or Gnome3 for instance?

**Comment by timothytylee** [comment]
Patch now done as a single commit on top of master as required.

The patch has been tested against KDE 4.11, MATE 1.8, Gnome 3.16 and Xfce 4.12

**Pull request merged**
